title: Enlight
description: "Enlight is a resource aimed to teach anyone to code through building projects. Hosting a wide variety of tutorials and demos, it provides users with sample projects and explains how they work."
url: https://tryenlight.github.io/enlight
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true
highlighter: none
